# pytest.ini
[pytest]
addopts = -vs --alluredir=allure-results --clean-alluredir
testpaths = frame/testcase
python_files = test_*.py
python_classes = Test*
python_functions = test_*

log_cli = true
log_cli_level = INFO

markers =
    smoke: 冒烟测试
    flow: 业务流测试
    regression: 回归测试