#测试环境
#把接口测试相关的配置数据提取出来，在yaml文件中进行保存
base_url: https://qyapi.weixin.qq.com/cgi-bin
#提取相关账户信息
corpid:
  接口自动化测试: ww36cf0d273af7a133
corpsecret:
  contacts: Ey1eTYQUDc01G34tkt8CZrjK6_tTQBh2j-dqRTn-t0U
  #contacts: cKCjTj5F-5JUOA6Hr1fC1RTtb8WKm37nNr2uouGYDgE



